[context]
name = "changelogging"
version = "0.5.0"
url = "https://github.com/nekitdev/changelogging"

[formats]
title = "[{{version}}]({{url}}/tree/v{{version}}) ({{date}})"
fragment = "{{content}} ([#{{id}}]({{url}}/pull/{{id}}))"
